project:
  type: website
  output-dir: report

website:
  title: "FLAG surveillance"
  favicon: "ðŸš©"
  navbar:
    background: "#3F3685"
    logo: "ðŸš©"
    left:
      - href: about.qmd
        text: About
      - href: est_weekly_report.qmd
        text: Report

format:
  html:
    css: _extensions/phs-html-quarto/phs_style.css
    toc: true

bibliography: references.bib

editor: visual
