project:
  type: website
  output-dir: report

website:
  title: "FLAG surveillance ðŸš©"
  favicon: _extensions/phs-html-quarto/favicon_phs.ico
  navbar:
    logo: _extensions/phs-html-quarto/phs-logo-white.png
    background: "#3F3685"
    left:
      - href: about.qmd
        text: About
      - href: est_weekly_report.qmd
        text: Report

format:
  html:
    css: _extensions/phs-html-quarto/phs_style.css
    toc: true

bibliography: references.bib

editor: visual
